// ⚠️ This file was generated by dotenv-never-lies
// Review and adjust schemas, descriptions and secrets before using
import { z } from "zod";
import { define } from "dotenv-never-lies";
export default define({
    // NODE_ENV: {
    //     description: "Environnement d’exécution",
    //     schema: z.enum(["test", "development", "staging", "production"]),
    //     //schema: z.union([z.literal("test"), z.literal("development"), z.literal("staging"), z.literal("production")]),
    //     //schema: z.literal("production"),
    //     examples: ["test", "development", "staging", "production"],
    // },
    // NODE_PORT: {
    //     description: "Port de l’API",
    //     schema: z.coerce.number().default(3000),
    //     examples: ["1000", "2000", "3000", "4000"],
    // },
    // JWT_SECRET: {
    //     description: "JWT Secret",
    //     schema: z.string().optional(),
    //     secret: true,
    // },
    // FRONT_SIMULATOR_RES: {
    //     schema: z.url(),
    //     description: "l'url de la page de simulation en mode res",
    // },
    // FRONT_SIMULATOR_RES_THERMIQUE: {
    //     schema: z.url(),
    //     description: "l'url de la page de simulation en mode thermique",
    // },
    // FRONT_SIMULATOR_PRO: {
    //     schema: z.url(),
    //     description: "l'url de la page de simulation en mode pro",
    // },
    FRONT_BO: {
        schema: z.url().optional(),
        description: "l'url de la page de back office",
    },
    NODE_CORS_ORIGIN: {
        schema: z.string().transform((v) => v
            .split(";")
            .map((s) => s.trim())
            .filter(Boolean)
            .map((url) => {
            // Validation email via Zod
            const res = z.url().safeParse(url);
            if (!res.success) {
                throw new Error(`NODE_CORS_ORIGIN contient une url invalide: "${url}"`);
            }
            return url;
        })),
        description: "les urls des front qui sont autorisés à faire des requêtes à cette API, séparées par des points-virgules",
    },
});
