// This file is auto-generated by src/infer/scripts/official-preset-registry.gen.ts
// Do not modify manually - run the script to regenerate (npm run gen:presets or yarn gen:presets)

import { InferPreset } from "./presets.types.js"
import { cookieParserPreset } from "./presets/cookie-parser.js"
import { cronPreset } from "./presets/cron.js"
import { expressSessionPreset } from "./presets/express-session.js"
import { googleMapsPreset } from "./presets/google-maps.js"
import { jsonwebtokenPreset } from "./presets/jsonwebtoken.js"
import { nodePreset } from "./presets/node.js"
import { nodemailerPreset } from "./presets/nodemailer.js"
import { prismaPreset } from "./presets/prisma.js"
import { stripePreset } from "./presets/stripe.js"
import { typeormPreset } from "./presets/typeorm.js"
import { vitestPreset } from "./presets/vitest.js"

export const officialPresetRegistry: Map<string, InferPreset> = new Map();

officialPresetRegistry.set(cookieParserPreset.origin, cookieParserPreset);
officialPresetRegistry.set(cronPreset.origin, cronPreset);
officialPresetRegistry.set(expressSessionPreset.origin, expressSessionPreset);
officialPresetRegistry.set(googleMapsPreset.origin, googleMapsPreset);
officialPresetRegistry.set(jsonwebtokenPreset.origin, jsonwebtokenPreset);
officialPresetRegistry.set(nodePreset.origin, nodePreset);
officialPresetRegistry.set(nodemailerPreset.origin, nodemailerPreset);
officialPresetRegistry.set(prismaPreset.origin, prismaPreset);
officialPresetRegistry.set(stripePreset.origin, stripePreset);
officialPresetRegistry.set(typeormPreset.origin, typeormPreset);
officialPresetRegistry.set(vitestPreset.origin, vitestPreset);
