import path from "node:path";
import dnl from "../../index.js";
import { guessSecret } from "../../infer/helpers.js";
import { crossInfer, infer } from "../utils/infer-rule-engine.js";
import fs from "node:fs";
import { ExportError } from "../../errors.js";
import { Import, InferContext } from "../../infer/rules.types.js";
import { discoverPresets, findPresetEntry, getPresetsFromNames } from "../../infer/presets.js";
import { PressetDef } from "../../infer/presets.types.js";
import { InferReportEntry, InferReport, EvaluatedRule, RuleMethod } from "../../infer/report.types.js";

export type InferCliOptions = {
    source?: string;
    out?: string;
    force?: boolean;
    guessSecret?: boolean; // if true, the command will not try to guess secret variables
    verbose?: boolean;
    warnOnDuplicates?: boolean;
    presets?: Array<string>;
    discoverPresets?: boolean;
};

export type InferResult = {
    content: string;
    out: string;
    warnings: string[];
    verbose?: Array<string>;
};

export const inferCommand = async (opts?: InferCliOptions | undefined): Promise<InferResult> => {
    const source = path.resolve(process.cwd(), opts?.source ?? ".env");
    if (!fs.existsSync(source)) {
        throw new ExportError(`Source env file not found: ${source}`);
    }
    const out = opts?.out ?? "env.dnl.ts";
    const target = path.resolve(process.cwd(), out);
    if (fs.existsSync(target) && !opts?.force) {
        throw new ExportError(`${out} already exists. Use --force to overwrite.`);
    }

    const warnings: string[] = [];
    let presets: Array<PressetDef> = [];

    // Preset selection strategy:
    // - `--presets ...`  -> use ONLY the provided presets (disables discovery)
    // - `--no-discover-presets` -> use no presets at all
    // - default -> discover presets from package.json
    const presetNames = (opts?.presets ?? []).filter((x): x is string => typeof x === "string" && x.length > 0);

    if (presetNames.length > 0) {
        presets = getPresetsFromNames(presetNames);
    } else if (opts?.discoverPresets === true) {
        presets = discoverPresets(warnings);
    } else {
        presets = [];
    }

    const env = dnl.readEnvFile(source, { onDuplicate: opts?.warnOnDuplicates ? "warn" : "error" }, warnings);

    const codeLines: string[] = [];

    const importedSchemas: Array<Import> = [
        { name: "define", from: "@romaintaillandier1978/dotenv-never-lies" },
        { name: "z", from: "zod" },
    ];
    const verbose: Array<string> = [];

    codeLines.push(`// ⚠️ This file was generated by dotenv-never-lies`);
    codeLines.push(`// Review and adjust schemas, descriptions and secrets before using`);
    codeLines.push("");
    codeLines.push("");
    codeLines.push(`export default define({`);

    const report: InferReport = {
        inputs: {
            source,
            presets: presets.map((p) => p.origin),
            discoverPresets: opts?.discoverPresets ?? true,
        },
        envVars: [],
    };
    for (const [name, rawValue] of Object.entries(env)) {
        console.log("looping on " + name + " : " + rawValue);

        const isValidIdentifier = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name);
        const safeKey = isValidIdentifier ? name : JSON.stringify(name);
        if (!isValidIdentifier) {
            warnings.push(`Key ${name} is not a valid identifier. It has been escaped to ${safeKey}.`);
        }

        codeLines.push(`    ${safeKey}: {`);
        verbose.push(`  Infer ${name} : `);

        const reportEntry: InferReportEntry = {
            envVarName: name,
            evaluatedRules: new Array<EvaluatedRule<RuleMethod>>(),
            warnings: new Array<string>(),
        };

        const pressetEvaluatedRules = findPresetEntry(presets, name);
        if (pressetEvaluatedRules) {
            console.log("Presset evaluated rules for " + name + " : " + pressetEvaluatedRules.length);
            console.log("   reportEntry.evaluatedRules.length before : " + reportEntry.evaluatedRules.length);
            reportEntry.evaluatedRules.push(...pressetEvaluatedRules);
            console.log("   reportEntry.evaluatedRules.length after : " + reportEntry.evaluatedRules.length);
        }
        const accepted = pressetEvaluatedRules?.find((r) => r.outcome === "accepted");
        if (accepted) {
            const {
                presetResult: { origin, entry },
            } = accepted;
            console.log("   Accepted for " + name + " : " + origin.join(", "));
            if (entry.schema.safeParse(rawValue).success) {
                codeLines.push(`        // from @preset ${origin.join(", ")}`);
                codeLines.push(`        description: "${entry.description}",`);
                codeLines.push(`        schema: ${entry.code},`);
                codeLines.push(`        secret: ${entry.secret ? "true" : "false"},`);
                if (entry.examples) {
                    codeLines.push(`        examples: ${JSON.stringify(entry.examples)},`);
                }
                codeLines.push(`    },`);
                importedSchemas.push(...entry.imports);
                report.envVars.push(reportEntry);
                continue;
            }

            accepted.outcome = "rejected";
            accepted.presetResult.reasons.push(`Value "${rawValue}" does not match preset schema`);

            warnings.push(`Preset "${origin}" ignored for ${name}: value "${rawValue}" does not match preset schema`);
        }

        codeLines.push(`        description: "TODO",`);

        const isSecret = (opts?.guessSecret ?? true) && guessSecret(name);

        // NO : if (rawValue === undefined || rawValue === '""' || rawValue === "''") { // WRONG !
        // Note: dotenv normalizes `FOO=`, `FOO=""` and `FOO=''` into an empty string ("").
        // At this stage, we only treat `undefined` as "variable not set".
        // Empty strings are handled by inference rules when relevant (e.g. number coercion).
        if (rawValue === undefined) {
            // undefined means the variable is not set in the .env file
            codeLines.push(`        schema: z.string().optional(),`);
        } else {
            const context: InferContext = { name, rawValue, imports: importedSchemas, reasons: verbose, codeWarnings: [] };

            const evaluatedRules = infer(context);
            reportEntry.evaluatedRules.push(...evaluatedRules);

            const generated = evaluatedRules.find((r) => r.outcome === "accepted")?.inferResult.generated;
            console.log("Accepted for " + name + " : " + generated?.kind);

            if (generated) {
                crossInfer({ inferredSchema: generated, isSecret, ...context });
                for (const w of context.codeWarnings) {
                    codeLines.push("        // " + w);
                }
                codeLines.push(`        schema: ${generated.code},`);
            }
        }
        if (isSecret) {
            codeLines.push(`        secret: true, //  ⚠️  inferred as secret`);
            verbose.push(`    -> inferred as secret`);
            warnings.push(`${name} inferred as secret`);
        }
        codeLines.push(`    },`);
        report.envVars.push(reportEntry);
    }

    codeLines.push(`});`);

    codeLines.push("/**");
    codeLines.push(" * ----------------------------------------------------------------------------------------------------------");
    codeLines.push(" * ℹ️ DNL TIP");
    codeLines.push(" *");
    codeLines.push(" * Once this schema is fully documented (descriptions, schemas, secrets, required flags),");
    codeLines.push(" * run:");
    codeLines.push(" *");
    codeLines.push(" *   dnl types");
    codeLines.push(" *");
    codeLines.push(" * This will generate `env.dnl.d.ts` and enable rich IntelliSense directly in your IDE.");
    codeLines.push(" *");
    codeLines.push(" * Docs: https://github.com/romaintaillandier1978/dotenv-never-lies/blob/master/docs/commands/types.md");
    codeLines.push(" *       dnl types --help");
    codeLines.push(" * ----------------------------------------------------------------------------------------------------------");
    codeLines.push(" */");

    // insert the imported schemas at the top of the file
    insertImports(codeLines, importedSchemas);

    console.log("infer report : " + JSON.stringify(report, null, 2));

    return {
        content: codeLines.join("\n"),
        out: target,
        warnings: [...warnings, "Generated schema is a prototype. Review schemas, descriptions and secrets before using."],
        verbose,
    };
};

const insertImports = (lines: string[], imports: Array<Import>): void => {
    if (!imports || imports.length === 0) return;
    const byFrom = new Map<string, Set<string>>();
    for (const imp of imports) {
        const current = byFrom.get(imp.from) ?? new Set<string>();
        current.add(imp.name);
        byFrom.set(imp.from, current);
    }
    const importLines: string[] = [];
    // tri par 'from' pour stabilité
    const froms = Array.from(byFrom.keys()).sort();
    for (const from of froms) {
        const names = Array.from(byFrom.get(from) ?? new Set<string>()).sort();
        if (names.length === 0) continue;
        importLines.push(`import { ${names.join(", ")} } from ${JSON.stringify(from)};`);
    }
    if (importLines.length === 0) return;
    lines.splice(3, 0, ...importLines);
};
