import path from "node:path";
import dnl from "../../index.js";
import { guessSecret, inferSchema } from "../utils/infer-schema.js";
import fs from "node:fs";
import { ExportError } from "../../errors.js";

export type InferCliOptions = {
    source?: string;
    out?: string;
    force?: boolean;
    guessSecret?: boolean;
};

export type InferResult = {
    content: string;
    out: string;
    warnings: string[];
};
export const inferCommand = async (opts?: InferCliOptions | undefined): Promise<InferResult> => {
    const source = path.resolve(process.cwd(), opts?.source ?? ".env");
    if (!fs.existsSync(source)) {
        throw new ExportError(`Source env file not found: ${source}`);
    }
    const out = opts?.out ?? "env.dnl.ts";
    const target = path.resolve(process.cwd(), out);
    if (fs.existsSync(target) && !opts?.force) {
        throw new ExportError(`${out} already exists. Use --force to overwrite.`);
    }

    const env = dnl.readEnvFile(source);
    const lines: string[] = [];
    const warnings: string[] = [];

    const importedSchemas = new Set<string>();

    lines.push(`// ⚠️ This file was generated by dotenv-never-lies`);
    lines.push(`// Review and adjust schemas, descriptions and secrets before using`);
    lines.push("");
    lines.push(`import { z } from "zod";`);
    lines.push(`import { define } from "@romaintaillandier1978/dotenv-never-lies";`);
    lines.push("");
    lines.push(`export default define({`);

    for (const [key, value] of Object.entries(env)) {
        const isValidIdentifier = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key);
        const safeKey = isValidIdentifier ? key : JSON.stringify(key);
        if (!isValidIdentifier) {
            warnings.push(`Key ${key} is not a valid identifier. It has been escaped to ${safeKey}.`);
        }
        lines.push(`    ${safeKey}: {`);
        lines.push(`        description: "TODO",`);
        if (value === undefined) {
            lines.push(`        schema: z.string().optional(),`);
        } else {
            lines.push(`        schema: ${inferSchema(key, value, importedSchemas)},`);
        }
        if (opts?.guessSecret && guessSecret(key)) {
            lines.push(`        secret: true,`);
        }
        lines.push(`    },`);
    }

    lines.push(`});`);

    // insert the imported schemas at the top of the file
    lines.splice(5, 0, `import { ${Array.from(importedSchemas).join(", ")} } from "@romaintaillandier1978/dotenv-never-lies";`);

    return {
        content: lines.join("\n"),
        out: target,
        warnings: [...warnings, "Generated schema is a prototype. Review schemas, descriptions and secrets before using."],
    };
};
