import path from "node:path";
import dnl from "../../index.js";
import { guessSecret, inferSchema } from "../utils/infer-schema.js";
import fs from "node:fs";

export const reverseEnvCommand = async (opts: { source: string; out: string; force?: boolean; guessSecret?: boolean }) => {
    const source = path.resolve(process.cwd(), opts.source);
    const out = opts.out ?? "env.dnl.ts";
    const target = path.resolve(process.cwd(), out);
    if (fs.existsSync(target) && !opts.force) {
        console.error(`❌ ${out} already exists. Use --force to overwrite.`);
        process.exit(1);
    }

    const env = dnl.readEnvFile(source);
    const lines: string[] = [];

    lines.push(`// ⚠️ This file was generated by dotenv-never-lies`);
    lines.push(`// Review and adjust schemas, descriptions and secrets before using`);
    lines.push("");
    lines.push(`import { z } from "zod";`);
    lines.push(`import { define } from "dotenv-never-lies";`);
    lines.push("");
    lines.push(`export default define({`);

    for (const [key, value] of Object.entries(env)) {
        lines.push(`    ${key}: {`);
        lines.push(`        description: "TODO",`);
        lines.push(`        schema: ${inferSchema(value)},`);
        if (opts.guessSecret && guessSecret(key)) {
            lines.push(`        secret: true,`);
        }
        lines.push(`    },`);
    }

    lines.push(`});`);

    fs.writeFileSync(target, lines.join("\n"));
};
