import path from "node:path";
import dnl from "../../index.js";
import { guessSecret, inferSchema } from "../utils/infer-schema.js";
import fs from "node:fs";
import { ExportError } from "../../errors.js";

export type ReverseEnvCliOptions = {
    source?: string;
    out?: string;
    force?: boolean;
    guessSecret?: boolean;
};

export type ReverseEnvResult = {
    content: string;
    out: string;
    warnings: string[];
};
export const reverseEnvCommand = async (opts?: ReverseEnvCliOptions | undefined): Promise<ReverseEnvResult> => {
    const source = path.resolve(process.cwd(), opts?.source ?? ".env");
    if (!fs.existsSync(source)) {
        throw new ExportError(`Source env file not found: ${source}`);
    }
    const out = opts?.out ?? "env.dnl.ts";
    const target = path.resolve(process.cwd(), out);
    if (fs.existsSync(target) && !opts?.force) {
        throw new ExportError(`${out} already exists. Use --force to overwrite.`);
    }

    const env = dnl.readEnvFile(source);
    const lines: string[] = [];

    lines.push(`// ⚠️ This file was generated by dotenv-never-lies`);
    lines.push(`// Review and adjust schemas, descriptions and secrets before using`);
    lines.push("");
    lines.push(`import { z } from "zod";`);
    lines.push(`import { define } from "dotenv-never-lies";`);
    lines.push("");
    lines.push(`export default define({`);

    for (const [key, value] of Object.entries(env)) {
        lines.push(`    ${key}: {`);
        lines.push(`        description: "TODO",`);
        lines.push(`        schema: ${inferSchema(value)},`);
        if (opts?.guessSecret && guessSecret(key)) {
            lines.push(`        secret: true,`);
        }
        lines.push(`    },`);
    }

    lines.push(`});`);

    return {
        content: lines.join("\n"),
        out: target,
        warnings: ["Generated schema is a prototype. Review schemas, descriptions and secrets before using."],
    };
};
